import type { Metadata } from "next";
import { Syne, Work_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "@/components/global-cmp/providers/query-provider";

const primary = Syne({
  subsets: ["latin"],
  variable: "--font-primary",
  display: 'swap',
});

const secondary = Work_Sans({  
  subsets: ["latin"],
  variable: "--font-secondary",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${primary.variable} ${secondary.variable} font-primary antialiased`}
      >
       <QueryProvider>
          {children}
        </QueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
